### ISSUE TITLE
runtime error: slice bounds out of range [-119:]

### ISSUE THREAD

**Issue by gerkra** [sijms/go-ora#105]
Hello!

In my case, I select query with data columns size more 255 bytes, and I get error:

**runtime error: slice bounds out of range [-119:]**
**network/session.go:1035**

```
if bigEndian {
		copy(temp[8-size:], rb) <-- Panic 
		ret = int64(binary.BigEndian.Uint64(temp))
	} else {
		copy(temp[:size], rb)
		//temp = append(pck.buffer[pck.index: pck.index + size], temp...)
		ret = int64(binary.LittleEndian.Uint64(temp))
	}
```

![image](https://user-images.githubusercontent.com/8065296/130441082-8b3f00d4-0ddb-49f8-b026-871bf0df22cc.png)

Please help me how to fix it. What settings are needed?

**Comment by gerkra** [comment]
@sijms help please!!

**Comment by gerkra** [comment]
![image](https://user-images.githubusercontent.com/8065296/130448685-74bccf86-23d9-4bc0-9b00-2fc9adb557d9.png)

**Comment by gerkra** [comment]
Maybe need do this?

v2/network/session.go:1097
`
size1, err = session.GetInt(1, false, false)
`

**Comment by sijms** [comment]
please can you tell me the query and column type?

**Comment by gerkra** [comment]
My query like this:

`SELECT mycolumn FROM mytable;`

1. Column type is varchar2(512)
2. LENGTHB show value 296 bytes

@sijms this is my case

**Comment by sijms** [comment]
client version: 1.2.1
server version: 12.2
this code is run completely without any error:
```
func TestIsuue105(conn *sql.DB) error {
	_, err := conn.Exec(`CREATE TABLE TEMP_ISSUE105 (
		TEMP_NAME VARCHAR2(512)
	)`)
	if err != nil {
		return err
	}
	defer func(conn *sql.DB) {
		_, err = conn.Exec(`DROP TABLE TEMP_ISSUE105`)
		if err != nil {
			fmt.Println(err)
		}
	}(conn)
	for x:=0; x < 10; x++ {
		_, err = conn.Exec(`INSERT INTO TEMP_ISSUE105(TEMP_NAME) VALUES(:1)`, strings.Repeat("0", 296))
		if err != nil {
			return err
		}
	}
	rows, err := conn.Query("SELECT TEMP_NAME FROM TEMP_ISSUE105")
	if err != nil {
		return err
	}
	var name string
	var index int
	for rows.Next() {
		err = rows.Scan(&name)
		if err != nil {
			return err
		}
		fmt.Println("index: ", index, "\tData: ", name)
		index ++
	}
	return rows.Err()

}
```
the result:
```
index:  0       Data:  00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
index:  1       Data:  00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
index:  2       Data:  00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
index:  3       Data:  00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
index:  4       Data:  00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
index:  5       Data:  00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
index:  6       Data:  00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
index:  7       Data:  00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
index:  8       Data:  00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
index:  9       Data:  00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
```

**Comment by gerkra** [comment]
Can You try save to data string like this "ОТДЕЛ ОФОРМЛЕНИЯ" (repeat to more 255 bytes) and test this.

I think you get error only on cyrillic characters.

Sorry for my english )

@sijms

**Comment by sijms** [comment]
ok no problem
tell me exactly which charset I will use
I will create database with this charset and do test again with Cyrillic character

**Comment by lingdian-cn** [comment]
### I have the same problem.  
sijms hello！
I test:
when the “oracle 11g”  is wrong.
when the “oracle 12c” is ok.
why？

### For Example: 
`github.com/sijms/go-ora/v2@v2.2.4`
#### Create Table:
`CREATE TABLE "T_USER" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"REMARK" VARCHAR2(1500),
	 PRIMARY KEY ("ID")
   ) `

#### QUERY:
`SELECT REMARK FROM T_USER`

An error occurs when the field 'REMARK' is greater than 252 characters.

The error message is as follows
```
panic: runtime error: slice bounds out of range [-117:]

goroutine 1 [running]:
github.com/sijms/go-ora/v2/network.(*Session).GetInt64(0xc0001ac000, 0x7d, 0x770101, 0xc0001ac000, 0x4, 0x101)
        A:/1_installed/cache_data/Golang/mod_cache/github.com/sijms/go-ora/v2@v2.2.4/network/session.go:859 +0x229
github.com/sijms/go-ora/v2/network.(*Session).GetInt(0xc0001ac000, 0x1, 0xc000220101, 0x1, 0x185, 0x0)
        A:/1_installed/cache_data/Golang/mod_cache/github.com/sijms/go-ora/v2@v2.2.4/network/session.go:872 +0x52
github.com/sijms/go-ora/v2/network.(*Session).GetClr(0xc0001ac000, 0xc00022e258, 0x0, 0x0, 0x0, 0x0)
        A:/1_installed/cache_data/Golang/mod_cache/github.com/sijms/go-ora/v2@v2.2.4/network/session.go:921 +0x210
github.com/sijms/go-ora/v2.(*defaultStmt).read(0xc0001aa820, 0xc0001be700, 0x0, 0x0)
        A:/1_installed/cache_data/Golang/mod_cache/github.com/sijms/go-ora/v2@v2.2.4/command.go:603 +0x98d
github.com/sijms/go-ora/v2.(*Stmt).Query(0xc0001aa820, 0xc0001a8600, 0x1, 0x1, 0x1, 0x1, 0x0, 0x0)
        A:/1_installed/cache_data/Golang/mod_cache/github.com/sijms/go-ora/v2@v2.2.4/command.go:1314 +0x445
database/sql.ctxDriverStmtQuery(0x8dd4b0, 0xc0000ac088, 0x8dd670, 0xc0001aa820, 0xc000182510, 0x1, 0x1, 0x1, 0x1, 0x0, ...)
        A:/1_installed/Go/src/database/sql/ctxutil.go:94 +0x16f
database/sql.rowsiFromStatement(0x8dd4b0, 0xc0000ac088, 0x8dc9d8, 0xc0001a4000, 0xc0001ba700, 0xc0001a8570, 0x1, 0x1, 0x0, 0x0, ...)
        A:/1_installed/Go/src/database/sql/sql.go:2695 +0x175
database/sql.(*Stmt).QueryContext(0xc000180480, 0x8dd4b0, 0xc0000ac088, 0xc0001a8570, 0x1, 0x1, 0x0, 0x0, 0x0)
        A:/1_installed/Go/src/database/sql/sql.go:2647 +0x22d
database/sql.(*Stmt).Query(...)
        A:/1_installed/Go/src/database/sql/sql.go:2685
iflybank-go/src/utils.(*DbUtil).QueryList(0xe35bc0, 0x879225, 0x1df, 0xc0000d7708, 0xc0001a8570, 0x1, 0x1, 0x0, 0x0)
        A:/2_project/idea/IFlyBank/iflybank-go/src/utils/db_util.go:131 +0x38e
iflybank-go/src/service.FindGradeRuleLikeName(0xc0000d7c48, 0xc0000ac080, 0x3, 0xc0001f4700, 0xb, 0x64)
        A:/2_project/idea/IFlyBank/iflybank-go/src/service/all_service_impl.go:85 +0x14b
iflybank-go/src/service.FindAllLikeName(0xc0000c5620, 0x85bf6d, 0x8, 0x85b991, 0x6, 0x9, 0x85b8b9, 0x6)
        A:/2_project/idea/IFlyBank/iflybank-go/src/service/all_service_impl.go:31 +0x1ae
main.main()
        A:/2_project/idea/IFlyBank/iflybank-go/src/main.go:49 +0x42f

```
 help me. please! thank you !
