### ISSUE TITLE
panic: runtime error: slice bounds out of range [-117:]

### ISSUE THREAD

**Issue by lingdian-cn** [sijms/go-ora#118]
### I have the same problem.  
hello！sijms ：

The Problem:
> 1、when the “oracle 11g”  is wrong.

![image](https://user-images.githubusercontent.com/42515123/137580707-9882eff2-788a-42d9-adad-5029863b6141.png)

> 2、when the “oracle 12c” is ok.

> 3、other versions of Oracle? I‘m not tested.

excuse me，why is there such a problem？

### For Example: 
`github.com/sijms/go-ora/v2@v2.2.4`
#### Create Table:
`CREATE TABLE "T_USER" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"REMARK" VARCHAR2(1500),
	 PRIMARY KEY ("ID")
   ) `

#### QUERY:
`SELECT REMARK FROM T_USER`

An error occurs when the field 'REMARK' is greater than 252 characters.

#### Field 'REMARK' values like this （253 ’a‘ in total）
```
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
```

#### The error message is as follows
```
panic: runtime error: slice bounds out of range [-117:]

goroutine 1 [running]:
github.com/sijms/go-ora/v2/network.(*Session).GetInt64(0xc0001ac000, 0x7d, 0x770101, 0xc0001ac000, 0x4, 0x101)
        A:/1_installed/cache_data/Golang/mod_cache/github.com/sijms/go-ora/v2@v2.2.4/network/session.go:859 +0x229
github.com/sijms/go-ora/v2/network.(*Session).GetInt(0xc0001ac000, 0x1, 0xc000220101, 0x1, 0x185, 0x0)
        A:/1_installed/cache_data/Golang/mod_cache/github.com/sijms/go-ora/v2@v2.2.4/network/session.go:872 +0x52
github.com/sijms/go-ora/v2/network.(*Session).GetClr(0xc0001ac000, 0xc00022e258, 0x0, 0x0, 0x0, 0x0)
        A:/1_installed/cache_data/Golang/mod_cache/github.com/sijms/go-ora/v2@v2.2.4/network/session.go:921 +0x210
github.com/sijms/go-ora/v2.(*defaultStmt).read(0xc0001aa820, 0xc0001be700, 0x0, 0x0)
        A:/1_installed/cache_data/Golang/mod_cache/github.com/sijms/go-ora/v2@v2.2.4/command.go:603 +0x98d
github.com/sijms/go-ora/v2.(*Stmt).Query(0xc0001aa820, 0xc0001a8600, 0x1, 0x1, 0x1, 0x1, 0x0, 0x0)
        A:/1_installed/cache_data/Golang/mod_cache/github.com/sijms/go-ora/v2@v2.2.4/command.go:1314 +0x445
database/sql.ctxDriverStmtQuery(0x8dd4b0, 0xc0000ac088, 0x8dd670, 0xc0001aa820, 0xc000182510, 0x1, 0x1, 0x1, 0x1, 0x0, ...)
        A:/1_installed/Go/src/database/sql/ctxutil.go:94 +0x16f
database/sql.rowsiFromStatement(0x8dd4b0, 0xc0000ac088, 0x8dc9d8, 0xc0001a4000, 0xc0001ba700, 0xc0001a8570, 0x1, 0x1, 0x0, 0x0, ...)
        A:/1_installed/Go/src/database/sql/sql.go:2695 +0x175
database/sql.(*Stmt).QueryContext(0xc000180480, 0x8dd4b0, 0xc0000ac088, 0xc0001a8570, 0x1, 0x1, 0x0, 0x0, 0x0)
        A:/1_installed/Go/src/database/sql/sql.go:2647 +0x22d
database/sql.(*Stmt).Query(...)
        A:/1_installed/Go/src/database/sql/sql.go:2685
iflybank-go/src/utils.(*DbUtil).QueryList(0xe35bc0, 0x879225, 0x1df, 0xc0000d7708, 0xc0001a8570, 0x1, 0x1, 0x0, 0x0)
        A:/2_project/idea/IFlyBank/iflybank-go/src/utils/db_util.go:131 +0x38e
iflybank-go/src/service.FindGradeRuleLikeName(0xc0000d7c48, 0xc0000ac080, 0x3, 0xc0001f4700, 0xb, 0x64)
        A:/2_project/idea/IFlyBank/iflybank-go/src/service/all_service_impl.go:85 +0x14b
iflybank-go/src/service.FindAllLikeName(0xc0000c5620, 0x85bf6d, 0x8, 0x85b991, 0x6, 0x9, 0x85b8b9, 0x6)
        A:/2_project/idea/IFlyBank/iflybank-go/src/service/all_service_impl.go:31 +0x1ae
main.main()
        A:/2_project/idea/IFlyBank/iflybank-go/src/main.go:49 +0x42f

```
 help me. please! thank you ! @sijms 

_Originally posted by @lingdian-cn in https://github.com/sijms/go-ora/issues/105#issuecomment-944879330_

**Comment by sijms** [comment]
you can test the following function
```
func Test253String(conn *sql.DB) error {
	_, err := conn.Exec(`CREATE TABLE "T_USER" ( "ID" NUMBER NOT NULL ENABLE, "REMARK" VARCHAR2(1500), PRIMARY KEY ("ID") )`)
	if err != nil {
		return err
	}
	defer func() {
		_, err = conn.Exec(`DROP TABLE "T_USER"`)
	}()
	text := strings.Repeat("a", 254)
	_, err = conn.Exec(`INSERT INTO "T_USER" ("ID", "REMARK") VALUES(1, :1)`, text)
	if err != nil {
		return err
	}
	row := conn.QueryRow(`SELECT "ID", "REMARK" FROM "T_USER"`)
	var remark string
	var id int64
	if row != nil {
		err = row.Scan(&id, &remark)
		if err != nil {
			return err
		}
		fmt.Println("ID: ", id)
		fmt.Println("REMARK: ", remark)
	}
	return nil
}
```

**Comment by lingdian-cn** [comment]
> you can test the following function
> 
> ```
> func Test253String(conn *sql.DB) error {
> 	_, err := conn.Exec(`CREATE TABLE "T_USER" ( "ID" NUMBER NOT NULL ENABLE, "REMARK" VARCHAR2(1500), PRIMARY KEY ("ID") )`)
> 	if err != nil {
> 		return err
> 	}
> 	defer func() {
> 		_, err = conn.Exec(`DROP TABLE "T_USER"`)
> 	}()
> 	text := strings.Repeat("a", 253)
> 	_, err = conn.Exec(`INSERT INTO "T_USER" ("ID", "REMARK") VALUES(1, :1)`, text)
> 	if err != nil {
> 		return err
> 	}
> 	row := conn.QueryRow(`SELECT "ID", "REMARK" FROM "T_USER"`)
> 	var remark string
> 	var id int64
> 	if row != nil {
> 		err = row.Scan(&id, &remark)
> 		if err != nil {
> 			return err
> 		}
> 		fmt.Println("ID: ", id)
> 		fmt.Println("REMARK: ", remark)
> 	}
> 	return nil
> }
> ```
> 
> change 253 to whatever you want


Hi~  I tried again,but it was still no go.

### main.go
```
package main

import (
	"database/sql"
	"fmt"
	_ "github.com/sijms/go-ora/v2"
	"strings"
)

func main() {
	// todo 1、Oracle Database 11g Enterprise Edition Release 11.2.0.1.0 - 64bit Production -- fail
	conn, _ := sql.Open("oracle", "oracle://finscloud:123456@10.0.0.17:1521/fscloud")
	
	// todo 2、Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production -- ok
	// conn, _ := sql.Open("oracle", "oracle://finscloud:finscloud@127.0.0.1:1521/ORACLEDB")
	Test253String(conn)
}

func Test253String(conn *sql.DB) error {
	_, err := conn.Exec(`CREATE TABLE "T_USER" ( "ID" NUMBER NOT NULL ENABLE, "REMARK" VARCHAR2(1500), PRIMARY KEY ("ID") )`)
	if err != nil {
		return err
	}
	defer func() {
		_, err = conn.Exec(`DROP TABLE "T_USER"`)
	}()
	text := strings.Repeat("a", 254)
	_, err = conn.Exec(`INSERT INTO "T_USER" ("ID", "REMARK") VALUES(1, :1)`, text)
	if err != nil {
		return err
	}
	row := conn.QueryRow(`SELECT "ID", "REMARK" FROM "T_USER"`)
	var remark string
	var id int64
	if row != nil {
		err = row.Scan(&id, &remark)
		if err != nil {
			return err
		}
		fmt.Println("ID: ", id)
		fmt.Println("REMARK: ", remark)
	}
	return nil
}

```

### 1、test result

> Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production

```
ID:  1
REMARK:  aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

```


### 2、test result

> Oracle Database 11g Enterprise Edition Release 11.2.0.1.0 - 64bit Production

```
panic: runtime error: slice bounds out of range [-118:]
goroutine 1 [running]:
github.com/sijms/go-ora/v2/network.(*Session).GetInt64(0xc000106000, 0x7e, 0x600101, 0xc000106000, 0x4, 0x101)
        A:/4_GOPATH/bin/pkg/mod/github.com/sijms/go-ora/v2@v2.2.4/network/session.go:859 +0x229
github.com/sijms/go-ora/v2/network.(*Session).GetInt(0xc000106000, 0x1, 0xc000150101, 0x1, 0x164, 0x0)
        A:/4_GOPATH/bin/pkg/mod/github.com/sijms/go-ora/v2@v2.2.4/network/session.go:872 +0x52
github.com/sijms/go-ora/v2/network.(*Session).GetClr(0xc000106000, 0xc0000b8ea0, 0x0, 0x0, 0x0, 0x0)
        A:/4_GOPATH/bin/pkg/mod/github.com/sijms/go-ora/v2@v2.2.4/network/session.go:921 +0x210
github.com/sijms/go-ora/v2.(*defaultStmt).read(0xc000094a00, 0xc00010c620, 0x0, 0x0)
        A:/4_GOPATH/bin/pkg/mod/github.com/sijms/go-ora/v2@v2.2.4/command.go:603 +0x98d
github.com/sijms/go-ora/v2.(*Stmt).Query(0xc000094a00, 0xc0b3d0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        A:/4_GOPATH/bin/pkg/mod/github.com/sijms/go-ora/v2@v2.2.4/command.go:1314 +0x445
database/sql.ctxDriverStmtQuery(0x706870, 0xc00009e010, 0x7069f8, 0xc000094a00, 0xc0b3d0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        A:/2_install_software/jdk_sdk/go/src/database/sql/ctxutil.go:94 +0x16f
database/sql.rowsiFromStatement(0x706870, 0xc00009e010, 0x706338, 0xc000102000, 0xc0000f4680, 0x0, 0x0, 0x0, 0x0, 0x0, .
..)
        A:/2_install_software/jdk_sdk/go/src/database/sql/sql.go:2695 +0x175
database/sql.(*DB).queryDC(0xc0000a6f70, 0x706870, 0xc00009e010, 0x0, 0x0, 0xc0000f6120, 0xc000088a40, 0x6bcbde, 0x23, 0
x0, ...)
        A:/2_install_software/jdk_sdk/go/src/database/sql/sql.go:1680 +0x24b
database/sql.(*DB).query(0xc0000a6f70, 0x706870, 0xc00009e010, 0x6bcbde, 0x23, 0x0, 0x0, 0x0, 0x4ee201, 0xc0000f6120, ..
.)
        A:/2_install_software/jdk_sdk/go/src/database/sql/sql.go:1628 +0x145
database/sql.(*DB).QueryContext(0xc0000a6f70, 0x706870, 0xc00009e010, 0x6bcbde, 0x23, 0x0, 0x0, 0x0, 0x0, 0x40b7a5, ...)
        A:/2_install_software/jdk_sdk/go/src/database/sql/sql.go:1605 +0xe5
database/sql.(*DB).QueryRowContext(...)
        A:/2_install_software/jdk_sdk/go/src/database/sql/sql.go:1706
database/sql.(*DB).QueryRow(0xc0000a6f70, 0x6bcbde, 0x23, 0x0, 0x0, 0x0, 0x1)
        A:/2_install_software/jdk_sdk/go/src/database/sql/sql.go:1717 +0x92
main.Test253String(0xc0000a6f70, 0x0, 0x0)
        A:/2_project/IDEAWorkSpace/go/ifly-go/src/main.go:29 +0x226
main.main()
        A:/2_project/IDEAWorkSpace/go/ifly-go/src/main.go:13 +0x65
```

@sijms  suggest you test 'oracle 11' （Oracle Database 11g Enterprise Edition Release 11.2.0.1.0 - 64bit Production）.

**Comment by sijms** [comment]
fixed man 
thank you for your help you catch a very annoying bug that causes may of issue in the past and I cannot get it until now

**Comment by lingdian-cn** [comment]
> fixed man thank you for your help you catch a very annoying bug that causes a lot of issues in the past and I cannot get it until now

Ha ha, can you shoot this bug? Is it difficult?  I hope you can solve it as soon as possible. Thank you! Best wishs to you!
