### ISSUE TITLE
runtime panic: divide by zero when no rows returned

### ISSUE THREAD

**Issue by eatonphil** [sijms/go-ora#152]
The query executes correctly but this library panics when zero rows are returned.

```
panic: runtime error: integer divide by zero

goroutine 1 [running]:
github.com/sijms/go-ora/v2.(*DataSet).Next(0xc0006a4120, {0x59a3398, 0x0, 0x4156dbf})
	/Users/runner/go/pkg/mod/github.com/sijms/go-ora/v2@v2.2.17/data_set.go:320 +0x36a
database/sql.(*Rows).nextLocked(0xc0000da000)
	/usr/local/Cellar/go/1.17.5/libexec/src/database/sql/sql.go:2967 +0x111
database/sql.(*Rows).Next.func1()
	/usr/local/Cellar/go/1.17.5/libexec/src/database/sql/sql.go:2945 +0x2f
database/sql.withLock({0x4e251d8, 0xc0000da030}, 0xc00079aac0)
	/usr/local/Cellar/go/1.17.5/libexec/src/database/sql/sql.go:3396 +0x8c
database/sql.(*Rows).Next(0xc0000da000)
	/usr/local/Cellar/go/1.17.5/libexec/src/database/sql/sql.go:2944 +0x6f
github.com/multiprocessio/datastation/runner.EvalDatabasePanel.func3.1.3({0xc000130e40, 0xc000035ba0})
	/Users/runner/work/datastation/datastation/runner/database.go:387 +0x168
github.com/multiprocessio/datastation/runner.importAndRun(0x8, 0xc00079af18, 0xc00079af18, {0xc000120f80, 0x0}, {0xc000130e40, 0x27}, {0x0, 0x0, 0x0}, ...)
	/Users/runner/work/datastation/datastation/runner/sql.go:298 +0x17f
github.com/multiprocessio/datastation/runner.EvalDatabasePanel.func3.1(0x1)
	/Users/runner/work/datastation/datastation/runner/database.go:370 +0x196
github.com/multiprocessio/datastation/runner.withJSONArrayOutWriter.func1()
	/Users/runner/work/datastation/datastation/runner/file.go:68 +0x73
github.com/multiprocessio/datastation/runner.withJSONOutWriter({0x4e19840, 0xc000114ad8}, {0x4e045fc, 0x6}, {0x4e04600, 0x1}, 0xc00079b008)
	/Users/runner/work/datastation/datastation/runner/file.go:53 +0xb7
github.com/multiprocessio/datastation/runner.withJSONArrayOutWriter({0x4e19840, 0xc000114ad8}, 0xc000130f90)
	/Users/runner/work/datastation/datastation/runner/file.go:67 +0x65
github.com/multiprocessio/datastation/runner.withJSONArrayOutWriterFile(...)
	/Users/runner/work/datastation/datastation/runner/file.go:79
github.com/multiprocessio/datastation/runner.EvalDatabasePanel.func3({0xc0003bae60, 0x9}, {0xc0003bae6a, 0x4})
	/Users/runner/work/datastation/datastation/runner/database.go:369 +0x365
github.com/multiprocessio/datastation/runner.withRemoteConnection(0xc000381960, {0xc0003bae60, 0x4c7778b}, {0xc0003bae6a, 0x0}, 0x4e049e8)
	/Users/runner/work/datastation/datastation/runner/ssh.go:208 +0x650
github.com/multiprocessio/datastation/runner.EvalDatabasePanel(0xc0000b0990, 0x0, 0xc000793560, 0x0)
	/Users/runner/work/datastation/datastation/runner/database.go:353 +0x885
github.com/multiprocessio/datastation/runner.EvalContext.Eval({{{0xc000130c30, 0x24}, 0xc0004496c0, 0xc0003fde30, {0xc000130c60, 0x30}, 0x1388, {0xc00046db40, 0x5}}}, {0x7ff7bfeffc1d, ...}, ...)
	/Users/runner/work/datastation/datastation/runner/eval.go:106 +0x505
main.main()
	/Users/runner/work/datastation/datastation/runner/cmd/main.go:60 +0x47f
```

**Comment by sijms** [comment]
can you write the code example to let me reproduce the issue and fix

**Comment by eatonphil** [comment]
Sure thing!

```
$ go run main.go
panic: runtime error: integer divide by zero

goroutine 1 [running]:
github.com/sijms/go-ora/v2.(*DataSet).Next(0xc00014a240, {0x17bb820, 0x0, 0x0})
        /Users/philipeaton/go/pkg/mod/github.com/sijms/go-ora/v2@v2.2.22/data_set.go:325 +0x2c5
database/sql.(*Rows).nextLocked(0xc000160180)
        /usr/local/Cellar/go/1.17.3/libexec/src/database/sql/sql.go:2967 +0x111
database/sql.(*Rows).Next.func1()
        /usr/local/Cellar/go/1.17.3/libexec/src/database/sql/sql.go:2945 +0x2f
database/sql.withLock({0x12a52e0, 0xc0001601b0}, 0xc00015ded8)
        /usr/local/Cellar/go/1.17.3/libexec/src/database/sql/sql.go:3396 +0x8c
database/sql.(*Rows).Next(0xc000160180)
        /usr/local/Cellar/go/1.17.3/libexec/src/database/sql/sql.go:2944 +0x6f
main.main()
        /Users/philipeaton/tmp/crash-ora/main.go:22 +0xbc
exit status 2

~/tmp/crash-ora ⌚ 17:52:48
$ cat main.go
package main

import (
        "database/sql"

        _ "github.com/sijms/go-ora/v2"
)

func main() {
        db, err := sql.Open("oracle", "oracle://test:test@localhost/XEPDB1?")
        if err != nil {
                panic(err)
        }

        rows, err := db.Query("CREATE TABLE x (age clob)")
        if err != nil {
                panic(err)
        }

        defer rows.Close()

        for rows.Next() {}
}
```

**Comment by eatonphil** [comment]
You might say this is not what you intend Query to be used for but I'm writing a generic query UI and the user can enter generic queries. Some return values and some don't.

Other Go drivers don't panic when I call `db.Query` and it returns no rows.

**Comment by sijms** [comment]
Hi @eatonphil 
`CREATE TABLE` is executed with Exec function not Query
there is big difference between 2 function as Query will return a result set object either empty or has data but Exec will not return any result set 
and if you run `CREATE TABLE` statement with Query and get error is not issue in the driver

does this happen when you select from empty table?

**Comment by sijms** [comment]
by the way I add a protective code that return io.EOF from Next when dataset.Rows is nil

**Comment by eatonphil** [comment]
Yep that works. Thank you!

**Comment by muellerkyle** [comment]
Why would you use io.EOF rather than the standard of sql.ErrNoRows?

See:

https://pkg.go.dev/database/sql#pkg-variables

-and-

https://stackoverflow.com/questions/43091774/queryrow-scan-returns-error-if-row-doesnt-exist

**Comment by sijms** [comment]
If no rows found Next() function will return false and loop will not executed
