### ISSUE TITLE
Driver panics when trying to execute statement in transaction

### ISSUE THREAD

**Issue by eugene-vodyanko** [sijms/go-ora#184]
Hi there.

The driver panics when trying to execute a statement in a transaction:

```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/sijms/go-ora/v2/network.NewSummary(0xc000085a00)
       /go/pkg/mod/github.com/sijms/go-ora/v2@v2.4.14/network/summary_object.go:187 +0xb07
github.com/sijms/go-ora/v2.(*defaultStmt).read(0xc0001aa3c0, 0xc0000dd5f0)
       /go/pkg/mod/github.com/sijms/go-ora/v2@v2.4.14/command.go:483 +0x21b
github.com/sijms/go-ora/v2.(*Stmt).Exec(0xc0001aa3c0, {0xc0001a2800, 0x4, 0xc00025e000})
       /go/pkg/mod/github.com/sijms/go-ora/v2@v2.4.14/command.go:1357 +0x808
github.com/sijms/go-ora/v2.(*Stmt).ExecContext(0xc0001aa3c0, {0x3ffbf0, 0xc0000ba5b8}, {0xc0001aa320, 0x4, 0x4})
       /go/pkg/mod/github.com/sijms/go-ora/v2@v2.4.14/command.go:1291 +0x225
github.com/sijms/go-ora/v2.(*Connection).ExecContext(0x21b2e0, {0x3ffbf0, 0xc0000ba5b8}, {0x3ae2bd, 0x7b00000020},
{0xc0001aa320, 0x4, 0x4})
       /go/pkg/mod/github.com/sijms/go-ora/v2@v2.4.14/connection.go:1090 +0xd0
database/sql.ctxDriverExec({0x3ffbf0, 0xc0000ba5b8}, {0x28ab9894978, 0xc000112200}, {0x0, 0x0}, {0x3ae2bd, 0x0}, {0
xc0001aa320, 0x4, ...})
        C:/Program Files/Go/src/database/sql/ctxutil.go:31 +0x17d
database/sql.(*DB).execDC.func2()
        C:/Program Files/Go/src/database/sql/sql.go:1646 +0x175
database/sql.withLock({0x3fde60, 0xc0001a0090}, 0xc0000ddb70)
        C:/Program Files/Go/src/database/sql/sql.go:3396 +0x8c
database/sql.(*DB).execDC(0xc0000ddc60, {0x3ffbf0, 0xc0000ba5b8}, 0xc0001a0090, 0xc0000ddd20, {0x3ae2bd, 0x154}, {0
xc0000ddd80, 0x4, 0x4})
        C:/Program Files/Go/src/database/sql/sql.go:1641 +0x266
database/sql.(*Tx).ExecContext(0xc0001c8080, {0x3ffbf0, 0xc0000ba5b8}, {0x3ae2bd, 0x154}, {0xc0000ddd80, 0x4, 0x4})
        C:/Program Files/Go/src/database/sql/sql.go:2450 +0xb7
```

Output of a debugging message for a code snippet:
```
			fmt.Println("result.bindErrors len =", len(result.bindErrors))
			result.bindErrors[x].rowOffset, err = session.GetInt(4, true, true)
			if err != nil {
				return nil, err
			}
```

, accordingly, the output:
`result.bindErrors len = 0`

This situation manifests itself in competitive execution.

Maybe, you have recommendations or instructions?

Thanks!

**Comment by sijms** [comment]
would you write your code that produce the error

**Comment by eugene-vodyanko** [comment]
_would you write your code that produce the error_
Yes, no problem, only it will be slightly long...

The problem arises when calling a large stored operation with a weighty business logic.
But, if I did the debugging correctly, the problem is somewhere in the area of using the Oracle AQ PL/SQL API.

Some preparation will be required (I don't use golang to perform DDL, you can use SQL*PLus or an analog).

### Create Queue
```
begin
  dbms_aqadm.create_queue_table(queue_table        => 'some_queue_table',
                                queue_payload_type => 'raw');

  dbms_aqadm.create_queue(queue_name  => 'some_queue',
                          queue_table => 'some_queue_table');

  dbms_aqadm.start_queue(queue_name => 'some_queue');
end;
/
```

### Enqueue messeges
```
declare
  v_enqueue_options    DBMS_AQ.ENQUEUE_OPTIONS_T;
  v_message_properties DBMS_AQ.MESSAGE_PROPERTIES_T;
  v_message            RAW(1);
  v_msg_id             RAW(16);

begin
  for i in 1 .. 10 loop
    dbms_aq.enqueue(queue_name         => 'some_queue',
                    enqueue_options    => v_enqueue_options,
                    message_properties => v_message_properties,
                    payload            => v_message,
                    msgid              => v_msg_id);
    dbms_output.put_line(v_msg_id);
  end loop;
end;
/

commit;
/
```

The queue entry procedure will print the message IDs of the same type (the IDs will be different in your case):
```
DC4A16D7BA515E7BE05400144FFA9B52
DC4A16D7BA525E7BE05400144FFA9B52
...
```

### Let's create a procedure that encapsulates the dequeue logic
```
create or replace procedure dequeuByMsgID(
  p_item_id in varchar2
, r_item_count out int
)
is
  v_message           RAW(1);
  v_dequeue_options   DBMS_AQ.DEQUEUE_OPTIONS_T;
  v_messageProperties DBMS_AQ.MESSAGE_PROPERTIES_T;
  v_msg_id            RAW(16) := hextoraw(p_item_id);

  QUEUE_TIMEOUT exception;
  PRAGMA EXCEPTION_INIT(QUEUE_TIMEOUT, -25228);
  RESOURCE_BUSY exception;
  PRAGMA EXCEPTION_INIT( RESOURCE_BUSY, -54 );
  NO_MESSAGE  exception;
  pragma EXCEPTION_INIT(NO_MESSAGE,-25263);
begin
  v_dequeue_options.msgId        := v_msg_id;
  v_dequeue_options.navigation   := dbms_aq.NEXT_MESSAGE;
  v_dequeue_options.visibility   := dbms_aq.ON_COMMIT;
  v_dequeue_options.dequeue_mode := dbms_aq.REMOVE;
  v_dequeue_options.wait         := dbms_aq.NO_WAIT;

  begin
    dbms_aq.dequeue(queue_name         => 'some_queue',
                    dequeue_options    => v_dequeue_options,
                    message_properties => v_messageProperties,
                    payload            => v_message,
                    msgid              => v_msg_id);

    dbms_output.put_line(v_msg_id);
    r_item_count := 1;
    return;
  exception
    when QUEUE_TIMEOUT then
      null;
    when RESOURCE_BUSY then
      null;
    when NO_MESSAGE then
      null;
  end;
  r_item_count := 0;
end;
```

### Finally golang code
```
package main

import (
	"database/sql"
	"fmt"
	_ "github.com/sijms/go-ora/v2"
	"log"
	"time"
)

var dbConf = map[string]string{
	"username": "*",
	"password": "*,
	"server":   "*",
	"port":     "*",
	"sid":	"*",
}

var msgID = "DC4A16D7BA545E7BE05400144FFA9B52"

func main() {
	connectionString := "oracle://" + dbConf["username"] + ":" + dbConf["password"] + "@" + dbConf["server"] + ":" + dbConf["port"] + "/" + dbConf["sid"]

	db, err := sql.Open("oracle", connectionString)
	db.SetMaxOpenConns(10)

	if err != nil {
		log.Fatal(err)
	}

	for i := 0; i < 10; i++ {
		go callProc(db, msgID)
	}

	time.Sleep(5*time.Second)
}

func callProc(db *sql.DB, msgID string) {
	query :="begin dequeuByMsgID(:1, :2); end;"

	var itemCount int

	tx, err := db.Begin()
	if err != nil {
		log.Fatal(err)
	}
	_, err = tx.Exec(query, msgID, sql.Out{Dest: &itemCount},
	)

	if err != nil {
		log.Fatal(err)
	}

	fmt.Println(itemCount)

	err = tx.Commit()
	if err != nil {
		log.Fatal(err)
	}

	return
}
```
Note that in addition to the DB connection parameters, you will also need to parameterize the value for msgID by taking one of the ones obtained when executing the Enqueue script above.

Thank You!

**Comment by sijms** [comment]
fixed you can test it = last version

**Comment by eugene-vodyanko** [comment]
It helped. Thanks a lot!
