### ISSUE TITLE
Driver panics when call cursor.Query()

### ISSUE THREAD

**Issue by eugene-vodyanko** [sijms/go-ora#187]
Hi there.

When working under load, when a function stored in the database is periodically called that returns a reference to the cursor, a crash occurs:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x7ff1ff]

goroutine 1 [running]:
github.com/sijms/go-ora/v2/network.(*Session).ResetBuffer(...)
	C:/Users/vodyanko/go/pkg/mod/github.com/sijms/go-ora/v2@v2.4.15/network/session.go:130
github.com/sijms/go-ora/v2.(*RefCursor).Query(0xc00028e000)
	C:/Users/vodyanko/go/pkg/mod/github.com/sijms/go-ora/v2@v2.4.15/ref_cursor.go:98 +0xff
solr-pfm-gate/internal/app/store.(*QueueRepository).Browse(0xc0000422a0)
	D:/work/go/solr-pfm-gate/internal/app/store/queuerepository.go:65 +0x226
solr-pfm-gate/internal/app/pfmgate.(*gate).processQueue(0xc0000500e0)
	D:/work/go/solr-pfm-gate/internal/app/pfmgate/gate.go:98 +0x14f
solr-pfm-gate/internal/app/pfmgate.(*gate).Start(0xc0000500e0)
	D:/work/go/solr-pfm-gate/internal/app/pfmgate/gate.go:56 +0x12b
solr-pfm-gate/internal/app/pfmgate.(*PFMGate).Start(0xc0000ddf38)
	D:/work/go/solr-pfm-gate/internal/app/pfmgate/pfmgate.go:46 +0x172
main.main()
	D:/work/go/solr-pfm-gate/cmd/pfmgate/main.go:49 +0x414

Process finished with the exit code 2
```

The method in which the cursor is organized has the form:
```
func (r *QueueRepository) Browse() ([]model.Group, error) {
	var row model.Group
	var ret []model.Group
	query :=
		"begin :1 := " +
			"slr$qmanager.getGroupIdCursor(" +
			"  p_queue_owner => :2" +
			", p_queue_name  => :3" +
			", p_queue_tab   => :4" +
			"); " +
			"end;"

	var cursor ora.RefCursor

	_, err := r.store.db.ExecContext(context.Background(), query,
		sql.Out{Dest: &cursor},
		r.queue.Config.In.QueueOwner,
		r.queue.Config.In.QueueName,
		r.queue.Config.In.QueueTable,
	)
	if err != nil {
		log.Fatal(err)
	}

	rows, err := cursor.Query()
	if err != nil {
		log.Fatal(err)
	}

	var count int
	for rows.Next_() {
		err = rows.Scan(&row.ID, &row.Count)
		if err != nil {
			log.Fatal(err)
		}
		count++
		ret = append(ret, row)
	}

	err = rows.Err()
	if err != nil {
		log.Fatal(err)
	}

	cursor.Close()

	return ret, nil
}
```

### It is important to note:

- The crash does not occur immediately, but after a certain number of successful executions.

- The problem is also affected by the presence of competitive coroutines that also work with the database.

- In addition, if you wrap the problematic code in a transaction ( _, err = tx.ExecContext(content.Background(), query), then the problem goes away -- although this is unnatural, because the function in the database has read only semantics and does not open any transformations explicit or implicit.

Maybe, you have recommendations or instructions?

Thanks!

P.S.
Unfortunately, I can't model yet to provide a compact and understandable self-sufficient code for reproduction.

**Comment by arashrahimi46** [comment]
have this issue

**Comment by sijms** [comment]
I am busy this week I will investigate the issue at the end of the week and inform you

**Comment by sijms** [comment]
I run 10 time after each other an no crach
but I use as store procedure not function:
```sql
CREATE OR REPLACE PROCEDURE GOORA_TEMP_GET_VISIT
(
	LVISIT_ID IN NUMBER,
	L_CURSOR OUT SYS_REFCURSOR
) AS
BEGIN
	OPEN L_CURSOR FOR SELECT VISIT_ID, NAME, VAL, VISIT_DATE FROM GOORA_TEMP_VISIT WHERE VISIT_ID > LVISIT_ID;
END GOORA_TEMP_GET_VISIT
```

**Comment by sijms** [comment]
I also change definition to function and call it many times without issue
```sql
CREATE OR REPLACE FUNCTION GOORA_TEMP_GET_VISIT
(
	LVISIT_ID IN NUMBER
) RETURN SYS_REFCURSOR AS
    L_CURSOR SYS_REFCURSOR;
BEGIN
	OPEN L_CURSOR FOR SELECT VISIT_ID, NAME, VAL, VISIT_DATE FROM GOORA_TEMP_VISIT WHERE VISIT_ID > LVISIT_ID;
	RETURN L_CURSOR;
END GOORA_TEMP_GET_VISIT;
```

calling
```golang
var cursor go_ora.RefCursor
_, err = conn.Exec(`BEGIN :1 := GOORA_TEMP_GET_VISIT(:2); END;`, sql.Out{Dest: &cursor}, 1)
```
may be the problem is related to the function body itself

**Comment by sijms** [comment]
@arashrahimi46 can you share your code may help in discovering the issue

**Comment by seed95** [comment]
Hi there,

I have same issue. When the program is running in concurrency mode and we call an SP that returns a reference to the cursor, panic occurs:

```

 panic: runtime error: invalid memory address or nil pointer dereference
         panic: runtime error: invalid memory address or nil pointer dereference
 [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5fd115]
 
 goroutine 35 [running]:
 github.com/sijms/go-ora/v2/network.(*Session).ResetBuffer(...)
         /home/sajad/go/pkg/mod/github.com/sijms/go-ora/v2@v2.4.16/network/session.go:130
 github.com/sijms/go-ora/v2.(*defaultStmt).Close(0x0)
         /home/sajad/go/pkg/mod/github.com/sijms/go-ora/v2@v2.4.16/command.go:1241 +0x35
 main.selectTicket.func2()
         /home/sajad/go/src/myissue/main.go:60 +0x1d
 panic({0x64daa0, 0xbc7460})
         /usr/local/go/src/runtime/panic.go:1038 +0x215
 github.com/sijms/go-ora/v2/network.(*Session).ResetBuffer(...)
         /home/sajad/go/pkg/mod/github.com/sijms/go-ora/v2@v2.4.16/network/session.go:130
 github.com/sijms/go-ora/v2.(*RefCursor).Query(0xc0001bc160)
         /home/sajad/go/pkg/mod/github.com/sijms/go-ora/v2@v2.4.16/ref_cursor.go:98 +0xff
 main.selectTicket(0x0)
         /home/sajad/go/src/myissue/main.go:66 +0x34b
 main.main.func1()
         /home/sajad/go/src/myissue/main.go:103 +0x33
 created by main.main
         /home/sajad/go/src/myissue/main.go:102 +0xb0

 Process finished with the exit code 2

```
Codes related to opening the database and the main:

```
func NewGooraDB() (*sql.DB, error) {
	dsn := `oracle://username:password@host:port/service`
	db, err := sql.Open("oracle", dsn)
	if err != nil {
		return nil, err
	}

	// Ping
	if err = db.Ping(); err != nil {
		return nil, err
	}

	return db, nil
}

func selectTicket(db *sql.DB) error {
	spName := "SP_SEL_TICKET_TEST"

	statusField := "IN_STATUS"
	pResultField := "P_OUT"

	fields := []string{statusField, pResultField}
	queryFields := strings.Join(fields, ",:")
	query := "BEGIN " + spName + "(:" + queryFields + "); END;"

	stmt, err := db.Prepare(query)
	if err != nil {
		return err
	}
	defer func() {
		err := stmt.Close()
		if err != nil {
			log.Println("closing_sql_statement", err)
		}
	}()

	var cursor go_ora.RefCursor
	_, err = stmt.Exec(
		sql.Named(statusField, sql.NullString{String: "ISSUED", Valid: true}),
		sql.Named(pResultField, sql.Out{Dest: &cursor}),
	)
	if err != nil {
		return err
	}
	defer func() {
		err := cursor.Close()
		if err != nil {
			log.Println("closing_go-ora_cursor", err)
		}
	}()

	rows, err := cursor.Query()
	if err != nil {
		return err
	}
	defer func() {
		err := rows.Close()
		if err != nil {
			log.Println("closing_oracle_rows", err)
		}
	}()

	var id sql.NullInt64
	for rows.Next_() {
		err = rows.Scan(&id)
		if err != nil {
			return err
		}

		fmt.Println("id:", id)
	}

	return nil
}



func main() {

	db, err := NewGooraDB()
	if err != nil {
		log.Fatal(err)
	}

	var wg sync.WaitGroup
	numConcurrency := 10

	for i := 1; i <= numConcurrency; i++ {
		wg.Add(1)
		go func() {
			err = selectTicket(db)
			if err != nil {
				fmt.Println("select ticket error:", err)
			}
			wg.Done()
		}()
	}

	wg.Wait()
}
```
The corresponding SP that runs inside the database

```
create or replace PROCEDURE                       SP_SEL_TICKET_TEST (
    IN_STATUS               VARCHAR2,
    P_OUT                   OUT SYS_REFCURSOR)
AS
    Query_clause   CLOB := '';
    Where_clause   CLOB := '';
BEGIN
    Query_clause := 'SELECT ID FROM MISC_SRV_ASAN_TICKETS.TICKET TIC';

    Where_clause := ' Where 1=1 ';
    Where_clause := where_clause || ' And  TIC.TIC_STATUS = ''' || IN_STATUS || '''';

    OPEN P_OUT FOR Query_Clause || where_clause;
END;
```

**Comment by sijms** [comment]
I will investigate the issue but as I understand from your code we have the following

`one DB connection` ----> used to create `10 RefCursor` ------> these RefCursor will reach `One Session Object`
concurrency must occur

so you need to use mutex whenever you use package directly

**Comment by sijms** [comment]
to manage this issue use one of the following:
1- use one connection object per goroutine
2- use mutex if you will share connection for more than one groutine 
3- I will try to create connection pooling for the driver but it will take time

**Comment by eugene-vodyanko** [comment]
@sijms, thank you for your clarifications and recommendations.
