### ISSUE TITLE
How do I connect go-ora to gorm?

### ISSUE THREAD

**Issue by madoleeee** [sijms/go-ora#302]
I tried to connect to gorm with the code below

```
db, err := gorm.Open(oracle.Open(go_ora.BuildJDBC(databaseInfo.Username, databaseInfo.UserPassword, databaseInfo.ConnectString, urlOptions)), &gorm.Config{})
	if err != nil {
		panic(err.Error())
	}
```

returns an error, can you give me a simple example of using gorm without errors?

```
panic: reflect: reflect.Value.Set using unaddressable value

goroutine 1 [running]:
reflect.flag.mustBeAssignableSlow(0x103a43e60?)
        /opt/homebrew/Cellar/go/1.19.3/libexec/src/reflect/value.go:260 +0x74
reflect.flag.mustBeAssignable(...)
        /opt/homebrew/Cellar/go/1.19.3/libexec/src/reflect/value.go:247
reflect.Value.Set({0x1039e95a0?, 0x1400000e798?, 0x103a43e60?}, {0x1039e95a0?, 0x1400013e378?, 0x140001f16e0?})
        /opt/homebrew/Cellar/go/1.19.3/libexec/src/reflect/value.go:2154 +0x54
gorm.io/gorm/schema.(*Field).setupValuerAndSetter.func6({0x103ac9bf0, 0x1400013e008}, {0x103a43e60?, 0x1400000e798?, 0x0?}, {0x1039d9a40, 0x1400013e378}, 0x1400000e5b8)
        /Users/choiyunseok/go/pkg/mod/gorm.io/gorm@v1.24.3/schema/field.go:558 +0x658
gorm.io/gorm/schema.(*Field).setupValuerAndSetter.func9({0x103ac9bf0?, 0x1400013e008?}, {0x103a43e60?, 0x1400000e798?, 0x140001f16e0?}, {0x1039d9a40?, 0x1400013e378?})
        /Users/choiyunseok/go/pkg/mod/gorm.io/gorm@v1.24.3/schema/field.go:714 +0x6c8
github.com/godoes/gorm-oracle.Create.func7(0x140004441e0)
        /Users/choiyunseok/go/pkg/mod/github.com/godoes/gorm-oracle@v1.3.16/create.go:137 +0xf8
reflect.Value.call({0x1039e68a0?, 0x1400049d300?, 0x103a1eec0?}, {0x1034eb3b6, 0x4}, {0x1400059d830, 0x1, 0x1033a13b4?})
        /opt/homebrew/Cellar/go/1.19.3/libexec/src/reflect/value.go:584 +0x688
reflect.Value.Call({0x1039e68a0?, 0x1400049d300?, 0x103a1eec0?}, {0x1400059d830?, 0x103a1eec0?, 0x140004f60f0?})
        /opt/homebrew/Cellar/go/1.19.3/libexec/src/reflect/value.go:368 +0x90
github.com/thoas/go-funk.ForEach({0x1039db580?, 0x1400000e960}, {0x1039e68a0?, 0x1400049d300})
        /Users/choiyunseok/go/pkg/mod/github.com/thoas/go-funk@v0.9.3/scan.go:40 +0x4a4
github.com/godoes/gorm-oracle.Create(0x140001f0db0)
        /Users/choiyunseok/go/pkg/mod/github.com/godoes/gorm-oracle@v1.3.16/create.go:130 +0xbec
gorm.io/gorm.(*processor).Execute(0x14000116280, 0x140004d5470?)
        /Users/choiyunseok/go/pkg/mod/gorm.io/gorm@v1.24.3/callbacks.go:130 +0x3e4
gorm.io/gorm.(*DB).Create(0x103a43e60?, {0x103a43e60?, 0x1400000e798})
        /Users/choiyunseok/go/pkg/mod/gorm.io/gorm@v1.24.3/finisher_api.go:24 +0xa8
github.com/sideweve/weveServerEcho/system/database.Setting()
        /Users/choiyunseok/project/weve_server_echo/system/database/setting.go:21 +0xd0
github.com/sideweve/weveServerEcho/system/server.Start()
        /Users/choiyunseok/project/weve_server_echo/system/server/server.go:29 +0x6c
main.main()
        /Users/choiyunseok/project/weve_server_echo/main.go:27 +0x1c
```

**Comment by sijms** [comment]
this code is working with me
```golang
package main

import (
	"fmt"
	oracle "github.com/godoes/gorm-oracle"
	"gorm.io/gorm"
	"os"
)

type Product struct {
	gorm.Model
	Code  string
	Price uint
}

func main() {
        // DSN contain database url 
        // you can use go_ora.BuildUrl function
	db, err := gorm.Open(oracle.Open(os.Getenv("DSN")), &gorm.Config{})
	if err != nil {
		panic("failed to connect database")
	}
	// Migrate the schema
	err = db.AutoMigrate(&Product{})
	if err != nil {
		panic("failed to migrate")
	}
	// Create
	db.Create(&Product{Model: gorm.Model{ID: 1, CreatedAt: time.Now(), UpdatedAt: time.Now()}, Code: "D42", Price: 100})

	// Read
	var product Product
	db.First(&product, 1) // find product with integer primary key
	fmt.Println(product)
	db.First(&product, "code = ?", "D42") // find product with code D42
	fmt.Println(product)
}
```

**Comment by dzwvip** [comment]
https://github.com/dzwvip/gorm-oracle
