### ISSUE TITLE
Nil *time.Time causes panic

### ISSUE THREAD

**Issue by eletrolitico** [sijms/go-ora#317]
The parameter encoder doesn't check if a parameter of type *time.Time is nil before encoding it. I don´t know if there are any specific reasons for this.

Here is the line: https://github.com/sijms/go-ora/blob/master/v2/parameter_encode.go#L319

**Comment by sijms** [comment]
i check for nil value [here](https://github.com/sijms/go-ora/blob/430ebecaa3ba4bfe18df4d372dac475f0198059d/v2/parameter_encode.go#L123)

**Comment by eletrolitico** [comment]
Here is a way to reproduce the panic: 

https://user-images.githubusercontent.com/13604284/224134451-ae9ca52e-61d5-474d-a824-9d8816d485d2.mp4



Log:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6500b4]

goroutine 1 [running]:
github.com/sijms/go-ora/v2.(*ParameterInfo).encodeValue(0xc0000f2ff0, {0x6bbcc0?, 0x0?}, 0x0, 0xc00011e480)
        /home/henrique/go/pkg/mod/github.com/sijms/go-ora/v2@v2.5.33/parameter_encode.go:319 +0x1f94
github.com/sijms/go-ora/v2.(*Stmt).NewParam(0xc0000b6280, {0x0, 0x0}, {0x6bbcc0, 0x0}, 0xc000129687?, 0x1)
        /home/henrique/go/pkg/mod/github.com/sijms/go-ora/v2@v2.5.33/command.go:1540 +0xda
github.com/sijms/go-ora/v2.(*Stmt).Exec(0xc0000b6280, {0xc0000a4250, 0x1, 0xc0000b40f0?})
        /home/henrique/go/pkg/mod/github.com/sijms/go-ora/v2@v2.5.33/command.go:1471 +0x3dc
github.com/sijms/go-ora/v2.(*Stmt).ExecContext(0xc0000b6280, {0x72f498?, 0xc00001a140}, {0xc0000d81b0, 0x1, 0x3?})
        /home/henrique/go/pkg/mod/github.com/sijms/go-ora/v2@v2.5.33/command.go:1420 +0x22b
github.com/sijms/go-ora/v2.(*Connection).ExecContext(0xc000129a00?, {0x72f498, 0xc00001a140}, {0x6cc3ad?, 0x4cce60?}, {0xc0000d81b0, 0x1, 0x1})
        /home/henrique/go/pkg/mod/github.com/sijms/go-ora/v2@v2.5.33/connection.go:1039 +0xd0
database/sql.ctxDriverExec({0x72f498?, 0xc00001a140?}, {0x7f25ce26e0d8?, 0xc00011e480?}, {0x0?, 0x0?}, {0x6cc3ad?, 0x6685a0?}, {0xc0000d81b0, 0x1, ...})
        /usr/lib/go/src/database/sql/ctxutil.go:31 +0xdd
database/sql.(*DB).execDC.func2()
        /usr/lib/go/src/database/sql/sql.go:1675 +0x175
database/sql.withLock({0x72e9f8, 0xc0000ac090}, 0xc000129ca8)
        /usr/lib/go/src/database/sql/sql.go:3405 +0x8c
database/sql.(*DB).execDC(0xc000129d01?, {0x72f498, 0xc00001a140}, 0xc0000ac090, 0x30?, {0x6cc3ad, 0x27}, {0xc000129f50, 0x1, 0x1})
        /usr/lib/go/src/database/sql/sql.go:1670 +0x266
database/sql.(*DB).exec(0x7f25f6deb088?, {0x72f498, 0xc00001a140}, {0x6cc3ad, 0x27}, {0xc000129f50, 0x1, 0x1}, 0x0?)
        /usr/lib/go/src/database/sql/sql.go:1655 +0xe8
database/sql.(*DB).ExecContext.func1(0x98?)
        /usr/lib/go/src/database/sql/sql.go:1634 +0x55
database/sql.(*DB).retry(0x72ea48?, 0xc000129ea0)
        /usr/lib/go/src/database/sql/sql.go:1538 +0x47
database/sql.(*DB).ExecContext(0x6bf7d1?, {0x72f498?, 0xc00001a140?}, {0x6cc3ad?, 0x4054dc?}, {0xc000129f50?, 0x407cd9?, 0x405531?})
        /usr/lib/go/src/database/sql/sql.go:1633 +0xcc
database/sql.(*DB).Exec(...)
        /usr/lib/go/src/database/sql/sql.go:1647
main.main()
        /home/henrique/tmp/panic_test/main.go:18 +0xb4
exit status 2

**Comment by sijms** [comment]
fixed in last release

**Comment by eletrolitico** [comment]
Thank you!
