### ISSUE TITLE
runtime: cannot allocate memory

### ISSUE THREAD

**Issue by zltningx** [sijms/go-ora#380]
When I use the following code to enumerate the sid of the service, a memory overflow error occurs. Is there something wrong with my code?

```
oc := new(go_ora.OracleDriver)
connector, err := oc.OpenConnector(fmt.Sprintf("oracle://%s/%s", address, serverName))
if err != nil {
return "", err
}
oConnector, ok := connector.(*go_ora.OracleConnector)
if !ok {
return "", errors.New("oracle connector")
}
oConnector.Dialer(&ProxyDialer)
db := sql.OpenDB(oConnector)
cc, cancel := context.WithTimeout(ctx, timeout)
defer cancel()
err = db.PingContext(cc)
if err != nil {
return err
}
defer db.Close()
```

```
fatal error: runtime: cannot allocate memory

goroutine 3 [running]:
runtime.throw({0x68ae7d?, 0x40b4d3?})
        runtime/panic.go:1047 +0x5d fp=0xc0000395f0 sp=0xc0000395c0 pc=0x434abd
runtime.newArenaMayUnlock()
        runtime/mheap.go:2149 +0xa5 fp=0xc000039620 sp=0xc0000395f0 pc=0x429585
runtime.newMarkBits(0x86e860?)
        runtime/mheap.go:2069 +0x145 fp=0xc000039668 sp=0xc000039620 pc=0x429205
runtime.(*sweepLocked).sweep(0x85db20?, 0x0)
        runtime/mgcsweep.go:636 +0x465 fp=0xc000039740 sp=0xc000039668 pc=0x424ba5
runtime.sweepone()
        runtime/mgcsweep.go:369 +0xf4 fp=0xc000039790 sp=0xc000039740 pc=0x424474
runtime.bgsweep(0x0?)
        runtime/mgcsweep.go:281 +0x105 fp=0xc0000397c8 sp=0xc000039790 pc=0x424225
runtime.gcenable.func1()
        runtime/mgc.go:178 +0x26 fp=0xc0000397e0 sp=0xc0000397c8 pc=0x419066
runtime.goexit()
        runtime/asm_amd64.s:1594 +0x1 fp=0xc0000397e8 sp=0xc0000397e0 pc=0x464621
created by runtime.gcenable
        runtime/mgc.go:178 +0x6b
```

**Comment by sijms** [comment]
sorry for late replay
I test this code and work correctly
```golang
package main

import (
	"context"
	"database/sql"
	"fmt"
	go_ora "github.com/sijms/go-ora/v2"
	"os"
	"time"
)

func main() {
	oc := new(go_ora.OracleDriver)
	connector, err := oc.OpenConnector(os.Getenv("DSN"))
	if err != nil {
		fmt.Println(err)
		return
	}
	oConnector, ok := connector.(*go_ora.OracleConnector)
	if !ok {
		fmt.Println(err)
		return
	}
	//oConnector.Dialer(&ProxyDialer)
	db := sql.OpenDB(oConnector)
	cc, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	err = db.PingContext(cc)
	if err != nil {
		fmt.Println(err)
		return
	}
	defer db.Close()
}
```
