### ISSUE TITLE
runtime error: slice bounds out of range [-61:]

### ISSUE THREAD

**Issue by savedev002** [sijms/go-ora#400]
I use github.com/jmoiron/sqlx with the go-ora@v2.7.8 and I have a connection error when trying to interact with the database after interacting once.  

This is the error I receive:

`runtime error: slice bounds out of range [-61:]
goroutine 12 [running]:
net/http.(*conn).serve.func1()
        C:/Program Files/Go/src/net/http/server.go:1854 +0xbf
panic({0x9e5b40, 0xc0000a8690})
        C:/Program Files/Go/src/runtime/panic.go:890 +0x263
github.com/sijms/go-ora/v2/network.(*Session).GetInt64(0xc000002000?, 0x1?, 0x38?, 0xa3?)
        C:/Users/TI05A100/go/pkg/mod/github.com/sijms/go-ora/v2@v2.7.8/network/session.go:1269 +0x192
github.com/sijms/go-ora/v2/network.(*Session).GetInt(...)
        C:/Users/TI05A100/go/pkg/mod/github.com/sijms/go-ora/v2@v2.7.8/network/session.go:1285
github.com/sijms/go-ora/v2/network.NewSummary(0xc000002000)
        C:/Users/TI05A100/go/pkg/mod/github.com/sijms/go-ora/v2@v2.7.8/network/summary_object.go:128 +0x4df
github.com/sijms/go-ora/v2.(*Connection).readResponse(0xc0005b0240, 0x1?)
        C:/Users/TI05A100/go/pkg/mod/github.com/sijms/go-ora/v2@v2.7.8/connection.go:1125 +0xc6
github.com/sijms/go-ora/v2.(*defaultStmt).read(0xc0002c0140, 0xc0004d6120)
        C:/Users/TI05A100/go/pkg/mod/github.com/sijms/go-ora/v2@v2.7.8/command.go:977 +0x415
github.com/sijms/go-ora/v2.(*Stmt)._query(0xc0002c0140)
        C:/Users/TI05A100/go/pkg/mod/github.com/sijms/go-ora/v2@v2.7.8/command.go:2392 +0x110
github.com/sijms/go-ora/v2.(*Stmt).Query_(0xc0002c0140, {0xc0004b84e0, 0x1, 0x0?})
        C:/Users/TI05A100/go/pkg/mod/github.com/sijms/go-ora/v2@v2.7.8/command.go:2301 +0x45b
github.com/sijms/go-ora/v2.(*Stmt).QueryContext(0xc0002c0140, {0xb4aff0?, 0xc000480140}, {0xc0004b84e0, 0x1, 0x1})
        C:/Users/TI05A100/go/pkg/mod/github.com/sijms/go-ora/v2@v2.7.8/command.go:2368 +0x1f4
github.com/sijms/go-ora/v2.(*Connection).QueryContext(0x276dab?, {0xb4aff0, 0xc000480140}, {0xa62b29?, 0x759660?}, {0xc0004b84e0, 0x1, 0x1})
        C:/Users/TI05A100/go/pkg/mod/github.com/sijms/go-ora/v2@v2.7.8/connection.go:1102 +0x86
database/sql.ctxDriverQuery({0xb4aff0?, 0xc000480140?}, {0x1ace373f158?, 0xc0005b0240?}, {0x0?, 0x0?}, {0xa62b29?, 0x2bfbba?}, {0xc0004b84e0, 0x1, ...})`

**Comment by sijms** [comment]
could you share the gocode which produce this error

**Comment by henkxie** [comment]
m

**Comment by savedev002** [comment]
I use `https://github.com/jmoiron/sqlx` , and as http framework i use echo. My problem originates when I finish a HTTP request and start another one. When processing the request I use the database a few times, the last interaction I have with the database in that HTTP request is using` sqlx.DB.ExecContext()`, apparently this execution blocks the interaction and the next request is no longer processed, I go back to process transactions until I make the request again, but the previous one throws me the error shared before. I have requests where I only use `sqlx.DB.GetContext() `and I have no problem. It is also important to clarify that the interaction of which I speak is made in a go routine, I ignore if this can be the origin of my problem with this driver, at the moment I use `github.com/godror/godror` and I have no inconvenience.

**Comment by sijms** [comment]
there was a problem related to insert + output parameter fixed in v2.7.11
would you please test again with this version

**Comment by savedev002** [comment]
I have the same error :(
