### ISSUE TITLE
"LOB FETCH: POST" ORA-01013: user requested cancel of current operation

### ISSUE THREAD

**Issue by UnderMountain96** [sijms/go-ora#407]
When I started using the database connection option **"LOB FETCH: POST"** in order to receive the blob field in its entirety, an error occurs, sometimes the request to the database hangs or gives the error **"ORA-01013: user requested cancel of current operation"**.

Without option **"LOB FETCH: POST"** everything works fine, only **BLOB size 32kb** 🙁

```
2023/07/20 15:06:59 ORA-01013: user requested cancel of current operation

panic: runtime error: slice bounds out of range [-90:]

goroutine 63 [running]:
github.com/sijms/go-ora/v2/network.(*Session).GetInt64(0xc000276000?, 0xc0004003cd?, 0x7c?, 0x1f?)
        C:/Users/_/go/pkg/mod/github.com/sijms/go-ora/v2@v2.7.9/network/session.go:1269 +0x192
github.com/sijms/go-ora/v2/network.(*Session).GetInt(...)
        C:/Users/_/go/pkg/mod/github.com/sijms/go-ora/v2@v2.7.9/network/session.go:1285
github.com/sijms/go-ora/v2/network.(*Session).GetClr(0xc000276000)
        C:/Users/_/go/pkg/mod/github.com/sijms/go-ora/v2@v2.7.9/network/session.go:1327 +0x19f
github.com/sijms/go-ora/v2.(*Lob).readData(0xc00026f838)
        C:/Users/_/go/pkg/mod/github.com/sijms/go-ora/v2@v2.7.9/lob.go:514 +0x28
github.com/sijms/go-ora/v2.(*Lob).read(0xc00026f838)
        C:/Users/_/go/pkg/mod/github.com/sijms/go-ora/v2@v2.7.9/lob.go:458 +0x265
github.com/sijms/go-ora/v2.(*Lob).getDataWithOffsetSize(0xc00026f838, 0x0, 0x0)
        C:/Users/_/go/pkg/mod/github.com/sijms/go-ora/v2@v2.7.9/lob.go:109 +0x278
github.com/sijms/go-ora/v2.(*Lob).getData(...)
        C:/Users/_/go/pkg/mod/github.com/sijms/go-ora/v2@v2.7.9/lob.go:119
github.com/sijms/go-ora/v2.setLob({0x8134e0?, 0xc00023c060?, 0x816fa0?}, {0xc000272000, {0xc00002a580, 0x72, 0x80}, {0x0, 0x0, 0x0}, ...})
        C:/Users/_/go/pkg/mod/github.com/sijms/go-ora/v2@v2.7.9/utils.go:649 +0x165
github.com/sijms/go-ora/v2.(*defaultStmt).decodePrim(0xc0001286e0?, 0xc000154480)
        C:/Users/_/go/pkg/mod/github.com/sijms/go-ora/v2@v2.7.9/command.go:2518 +0x7f8
github.com/sijms/go-ora/v2.(*RefCursor)._query(0xc0001286e0)
        C:/Users/_/go/pkg/mod/github.com/sijms/go-ora/v2@v2.7.9/ref_cursor.go:120 +0x114
github.com/sijms/go-ora/v2.(*RefCursor).Query(0xc0001286e0)
        C:/Users/_/go/pkg/mod/github.com/sijms/go-ora/v2@v2.7.9/ref_cursor.go:142 +0x125
_/internal/app/store/sqlstore.(*CitizenRepository).GetCardFiles(0xc00000a7e0, {0x954ca0, 0xc000197260}, 0x3220356220203065?, 0x4a18a5?)
        D:/projects/_/api/internal/app/store/sqlstore/citizenrepository.go:545 +0x2a5
_/internal/app/apiserver.(*server).handleGetCardFile.func1.1()
        D:/projects/_/api/internal/app/apiserver/handlers.go:495 +0x95
created by _/internal/app/apiserver.(*server).handleGetCardFile.func1
        D:/projects/_/api/internal/app/apiserver/handlers.go:494 +0x1cc
exit status 2
```

``` go

type File struct {
	ID        int64 `db:"name=ID" json:"id"`
	Data      []byte `db:"type=blob,name=DATA" json:"data"`
	Type      string `db:"name=TYPE" json:"type"`
	Size      int64  `db:"name=SIZE_F" json:"size"`
	Ext       string `db:"name=EXT" json:"etx"`
}

func newDB(database Database) (db *sql.DB, err error) {
	urlOptions := map[string]string{
		"TRACE FILE":         "logs/db.log",
		"CONNECTION TIMEOUT": database.ConnectionTimeout,
		"LOB FETCH":          "POST",
	}
	databaseURL := go_ora.BuildUrl(
		database.Server,
		database.Port,
		database.Service,
		database.Username,
		database.Password,
		urlOptions,
	)

	db, err = sql.Open("oracle", databaseURL)
	if err != nil {
		return nil, err
	}

	db.SetConnMaxIdleTime(time.Second * database.MaxIdleTime)
	db.SetConnMaxLifetime(time.Second * database.MaxLifeTime)
	db.SetMaxIdleConns(database.MaxIdleConns)
	db.SetMaxOpenConns(database.MaxOpenConns)

	return db, nil
}

func (s *server) handleGetFiles() http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		params := mux.Vars(r)
		id_str := params["id"]

		id, err := strconv.ParseInt(id_str, 10, 64)
		if err != nil {
			s.error(w, r, http.StatusBadRequest, err)
			return
		}

		var (
			rest []model.File
		)

		wg := sync.WaitGroup{}
		wg.Add(1)
		go func() {
			rest, err = Citizen().GetFiles(r.Context(), &wg, id)
		}()
		wg.Wait()

		if err != nil {
			s.error(w, r, http.StatusUnprocessableEntity, err)
			return
		}

		s.respond(w, r, http.StatusOK, rest)
	}
}

func (r *CitizenRepository) GetFiles(ctx context.Context, wg *sync.WaitGroup, id int64) (rest []model.File, err error) {
	defer wg.Done()
	conn, err := db.Conn(context.Background())
	if err != nil {
		return rest, err
	}

	defer conn.Close()

	var cursor go_ora.RefCursor
	rest = []model.File{}

	if _, err := conn.ExecContext(
		ctx,
		"BEGIN GET_FILES(:1,:2); END;",
		sql.Out{Dest: &cursor},
		id,
	); err != nil {
		return rest, err
	}

	defer func() {
		err = cursor.Close()
		if err != nil {
			log.Println(err)
		}
	}()

	rows, err := cursor.Query()
	if err != nil {
		return rest, err
	}

	for rows.Next_() {
		var f model.File
		err = rows.Scan(
			&f.ID,
			&f.Data,
			&f.Type,
			&f.Size,
			&f.Ext,
		)
		if err != nil {
			log.Println(err)
			return rest, err
		}

		rest = append(rest, f)
	}

	defer rows.Close()

	return rest, nil
}
```

``` sql
procedure GET_FILES(p_cursore out sys_refcursor, p_owner_id in number) 
  is 
  begin
    open p_cursore for
    SELECT id, data, type_f, size_f, ext from TB_FILE where owner_id = p_owner_id order by created_at desc;
end;
```

@sijms thanks for the help 🙏

**Comment by UnderMountain96** [comment]
Also tried without "LOB FETCH: POST", select BLOB separately

```go
func (r *CitizenRepository) GetFiles(ctx context.Context, wg *sync.WaitGroup, id int64) (rest []model.File, err error) {
	defer wg.Done()
	conn, err := db.Conn(context.Background())
	if err != nil {
		return rest, err
	}

	defer conn.Close()

	var cursor go_ora.RefCursor
	rest = []model.File{}

	if _, err := conn.ExecContext(
		ctx,
		"BEGIN GET_FILES(:1,:2); END;",
		sql.Out{Dest: &cursor},
		id,
	); err != nil {
		return rest, err
	}

	defer func() {
		err = cursor.Close()
		if err != nil {
			log.Println(err)
		}
	}()

	rows, err := cursor.Query()
	if err != nil {
		return rest, err
	}

	for rows.Next_() {
		var f model.File
		err = rows.Scan(
			&f.ID,
			//&f.Data,
			&f.Type,
			&f.Size,
			&f.Ext,
		)
		if err != nil {
			log.Println(err)
			return rest, err
		}
                // new code
                var blob go_ora.Blob

		if _, err := conn.ExecContext(
			ctx,
			"BEGIN GET_FILE_BLOB(:1,:2); END;",
			go_ora.Out{Dest: &blob, Size: f.Size},
			f.ID,
		); err != nil {
			log.Println(err)
			return rest, err
		}

		if blob.Valid {
			f.Data = blob.Data
		}

		rest = append(rest, f)
        }

	defer rows.Close()

	return rest, nil
}
```

the result is the same...

**Comment by sijms** [comment]
sorry for late replay
if you have lob `data > 32KB` you should use `lob fetch=post`
the error `ORA-01013: user requested cancel of current operation` occur because of timeout and driver will send a signal to cancel current operation so you should increase `global timeout url parameter default 30 seconds`

**Comment by Nihilus118** [comment]
@sijms is there a way to fully disable the builtin timeouts and only use the context functions?
I am experiencing the same error when using v2 of the driver combined with the stdlib, wrapped with sqlx.

**Comment by UnderMountain96** [comment]
#@sijms I use `lob fetch=post`, blob comes completely, blob downloaded +-10ms, but sometimes (1/10 or 1/20 1/x ...) execution query freezes and may continue very long or immediately after execution throw error `panic: runtime error: slice bounds out of range [-90:]`.
TimeOut does not have time to work, process freezes so i added context timeout 3s. (Call func -> started executing -> freezes -> throw error/contextTimeout)

it doesn't matter what file size (100kb, 500kb, 2mb)

i solved this problem: by making the api with 1 endpoint on RUST, everything works perfectly.

**Comment by sijms** [comment]
I update timeout to 120 second in last release 2.7.14 you can make it more

**Comment by Nihilus118** [comment]
@sijms Thank you! It would be nice to be able to fully disable the builtin timeout by specifying TIMEOUT=0

**Comment by sijms** [comment]
ok i will add it in next release and inform you here

**Comment by sijms** [comment]
disable timeout when set to 0 add to v2.7.15

**Comment by Nihilus118** [comment]
Thank you @sijms! When will it be released?

**Comment by sijms** [comment]
released

**Comment by Nihilus118** [comment]
Issue seems to be fixed. I did not encounter the error in the last 24 hours.
