### ISSUE TITLE
Panic in v2 `network.Session.GetInt64`: slice out of bounds

### ISSUE THREAD

**Issue by ccampo133** [sijms/go-ora#539]
```
panic: runtime error: slice bounds out of range [-46:]

goroutine 1738 [running]:
github.com/sijms/go-ora/v2/network.(*Session).GetInt64(0xc0012f48c0?, 0x7f4110ae3938?, 0x1?, 0x0?)
        /go/pkg/mod/github.com/sijms/go-ora/v2@v2.8.6/network/session.go:1462 +0x175
github.com/sijms/go-ora/v2/network.(*Session).GetInt(...)
        /go/pkg/mod/github.com/sijms/go-ora/v2@v2.8.6/network/session.go:1478
github.com/sijms/go-ora/v2/network.(*Session).GetDlc(0xc0012f48c0?)
        /go/pkg/mod/github.com/sijms/go-ora/v2@v2.8.6/network/session.go:1583 +0x28
github.com/sijms/go-ora/v2.(*ParameterInfo).load(0xc0069bc620, 0xc000d2a780)
        /go/pkg/mod/github.com/sijms/go-ora/v2@v2.8.6/parameter.go:274 +0x673
github.com/sijms/go-ora/v2.(*defaultStmt).read(0xc0070483c0, 0xc0010834d0)
        /go/pkg/mod/github.com/sijms/go-ora/v2@v2.8.6/command.go:944 +0x8dc
github.com/sijms/go-ora/v2.(*Stmt)._query(0xc0070483c0)
        /go/pkg/mod/github.com/sijms/go-ora/v2@v2.8.6/command.go:2279 +0xef
github.com/sijms/go-ora/v2.(*Stmt).Query_(0xc0070483c0, {0xc000fe24b0, 0x2, 0x0?})
        /go/pkg/mod/github.com/sijms/go-ora/v2@v2.8.6/command.go:2181 +0x2d6
github.com/sijms/go-ora/v2.(*Stmt).QueryContext(0xc0070483c0, {0x39daf08?, 0xc0011992c0}, {0xc000fe24b0, 0x2, 0x2})
        /go/pkg/mod/github.com/sijms/go-ora/v2@v2.8.6/command.go:2249 +0x1e6
github.com/sijms/go-ora/v2.(*Connection).QueryContext(0x4107c5?, {0x39daf08, 0xc0011992c0}, {0xc0037ba000?, 0x1befb80?}, {0xc000fe24b0, 0x2, 0x2})
        /go/pkg/mod/github.com/sijms/go-ora/v2@v2.8.6/connection.go:1094 +0x112
database/sql.ctxDriverQuery({0x39daf08?, 0xc0011992c0?}, {0x7f4110d84148?, 0xc000d2a780?}, {0x0?, 0x0?}, {0xc0037ba000?, 0x2?}, {0xc000fe24b0, 0x2, ...})
        /usr/local/go/src/database/sql/ctxutil.go:48 +0xd7
database/sql.(*DB).queryDC.func1()
        /usr/local/go/src/database/sql/sql.go:1748 +0x165
database/sql.withLock({0x39b95b0, 0xc000e137a0}, 0xc004c848e0)
        /usr/local/go/src/database/sql/sql.go:3502 +0x82
database/sql.(*DB).queryDC(0xc004c84901?, {0x39daf08?, 0xc0011992c0}, {0x0, 0x0}, 0xc000e137a0, 0xc001b36b80, {0xc0037ba000, 0x1d3c}, {0xc001235d48, ...})
        /usr/local/go/src/database/sql/sql.go:1743 +0x209
database/sql.(*DB).query(0xc000b68270?, {0x39daf08, 0xc0011992c0}, {0xc0037ba000, 0x1d3c}, {0xc004c84d48, 0x2, 0x2}, 0x40?)
        /usr/local/go/src/database/sql/sql.go:1726 +0xfc
database/sql.(*DB).QueryContext.func1(0x38?)
        /usr/local/go/src/database/sql/sql.go:1704 +0x4f
database/sql.(*DB).retry(0xc00260ba80?, 0xc001235ac8)
        /usr/local/go/src/database/sql/sql.go:1538 +0x42
database/sql.(*DB).QueryContext(0xc0037ba000?, {0x39daf08?, 0xc0011992c0?}, {0xc0037ba000?, 0xc004c84bb8?}, {0xc004c84d48?, 0xc004c84b98?, 0x1?})
        /usr/local/go/src/database/sql/sql.go:1703 +0xc5
```

Occurred calling `sql.DB.QueryContext(ctx, query, params...)` where the `query` looked something like:

```sql
SELECT "foo", "bar", "baz" FROM schema.table OFFSET :1 ROWS FETCH NEXT :2 ROWS ONLY
```

I'm not sure on the exact number of columns that were selected - it may have been a lot (`"foo", "bar", "baz"` is just a dummy example) as this code was intended to select every column on the table explicitly (as opposed to doing a `select *`).

The query parameters `params` was just limit and offset integers (e.g. `5` and `0`).

The connection string looked like:

```
oracle://user:password@host:1234/serviceName
```

Not sure on the Oracle version - I will update this issue with that information if I get it. Also this was v2.8.6 -I am not sure if this is corrected in the latest version: I couldn't tell from a quick glance at the code, and haven't been able to run the code with the latest version.

**Comment by sijms** [comment]
code using v2.8.11
```golang
package main

import (
	"database/sql"
	"fmt"
	_ "github.com/sijms/go-ora/v2"
	"os"
	"strconv"
	"time"
)

type TTB_DATA struct {
	Id   int64     `db:"ID"`
	Name string    `db:"NAME"`
	Val  float64   `db:"VAL"`
	Date time.Time `db:"LDATE"`
}

func execCmd(db *sql.DB, stmts ...string) error {
	for _, stmt := range stmts {
		if _, err := db.Exec(stmt); err != nil {
			if len(stmts) > 1 {
				return fmt.Errorf("error: %v in execuation of stmt: %s", err, stmt)
			} else {
				return err
			}
		}
	}
	return nil
}

func createTable(db *sql.DB) error {
	t := time.Now()
	err := execCmd(db, `CREATE TABLE TTB_539(
	ID			number(10)	NOT NULL,
	NAME		VARCHAR(200),
	VAL			number(10,2),
	LDATE	date,
	PRIMARY KEY(ID)
	)`)
	if err != nil {
		return err
	}
	fmt.Println("Finish create table :", time.Now().Sub(t))
	return nil
}

func dropTable(db *sql.DB) error {
	t := time.Now()
	err := execCmd(db, "drop table TTB_539 purge")
	if err != nil {
		return err
	}
	fmt.Println("Finish drop table: ", time.Now().Sub(t))
	return nil
}

func insert(conn *sql.DB, count int) error {
	t := time.Now()
	data := make([]TTB_DATA, count)
	for x := 0; x < count; x++ {
		data[x].Id = int64(1 + x)
		data[x].Name = "test_ " + strconv.Itoa(x+1)
		data[x].Val = 100.23 + 1
		data[x].Date = time.Now()

	}
	_, err := conn.Exec("INSERT INTO TTB_539 (ID, NAME, VAL, LDATE) VALUES(:ID, :NAME, :VAL, :LDATE)", data)
	if err != nil {
		return err
	}
	fmt.Println("Finish insert data: ", time.Now().Sub(t))
	return nil
}

func query(db *sql.DB) error {
	rows, err := db.Query("SELECT ID, NAME, VAL, LDATE FROM TTB_539 OFFSET :1 ROWS FETCH NEXT :2 ROWS ONLY", 5, 0)
	if err != nil {
		return err
	}
	defer func() {
		err = rows.Close()
		if err != nil {
			fmt.Println("can't close rows: ", err)
		}
	}()
	var (
		id   int
		name string
		val  float32
		date time.Time
	)
	for rows.Next() {
		err = rows.Scan(&id, &name, &val, &date)
		if err != nil {
			return err
		}
		fmt.Println("ID: ", id, "\tName: ", name, "\tVal: ", val, "\tDate: ", date)
	}
	return rows.Err()
}
func main() {
	db, err := sql.Open("oracle", os.Getenv("DSN"))
	if err != nil {
		fmt.Println("can't connect: ", err)
		return
	}
	defer func() {
		err = db.Close()
		if err != nil {
			fmt.Println("can't close connection: ", err)
		}
	}()

	err = createTable(db)
	if err != nil {
		fmt.Println("Can't create table: ", err)
		return
	}
	defer func() {
		err = dropTable(db)
		if err != nil {
			fmt.Println("Can't drop table: ", err)
		}
	}()
	err = insert(db, 100)
	if err != nil {
		fmt.Println("can't insert: ", err)
		return
	}
	err = query(db)
	if err != nil {
		fmt.Println("can't query: ", err)
		return
	}
}
```
result
```bash
Finish create table : 915.58439ms
Finish insert data:  107.28965ms
Finish drop table:  110.173939ms
```

**Comment by ccampo133** [comment]
The panic was experienced on Oracle 19c for what its worth.

**Comment by sijms** [comment]
the above code is running on oracle 19c also with no panic
please upgrade to latest version and test again
