### ISSUE TITLE
(*Number).decode panic: runtime error: index out of range [-1]

### ISSUE THREAD

**Issue by wmentor** [sijms/go-ora#579]
```
panic: runtime error: index out of range [-1]


goroutine 4233139 [running]:
github.com/sijms/go-ora/v2.(*Number).decode(0x10?)
        /home/builder/go/pkg/mod/github.com/sijms/go-ora/v2@v2.8.19/number.go:178 +0x236
github.com/sijms/go-ora/v2.(*Number).String(0xc00049e000?)
        /home/builder/go/pkg/mod/github.com/sijms/go-ora/v2@v2.8.19/number.go:247 +0x17
github.com/sijms/go-ora/v2.(*ParameterInfo).decodePrimValue(0xc0013951e0, 0xc00049c008, 0xc004ecd0d8, 0x0)
        /home/builder/go/pkg/mod/github.com/sijms/go-ora/v2@v2.8.19/parameter.go:550 +0x419
github.com/sijms/go-ora/v2.(*ParameterInfo).decodeColumnValue(0xc0013951e0?, 0xc00042d7f8?, 0x411e85?, 0x50?)
        /home/builder/go/pkg/mod/github.com/sijms/go-ora/v2@v2.8.19/parameter.go:779 +0x3c5
github.com/sijms/go-ora/v2.(*defaultStmt).calculateColumnValue(0xc00049e000?, 0x1?, 0x11?)
        /home/builder/go/pkg/mod/github.com/sijms/go-ora/v2@v2.8.19/command.go:1214 +0x132
github.com/sijms/go-ora/v2.(*defaultStmt).read(0xc004ecd040, 0xc00048df00)
        /home/builder/go/pkg/mod/github.com/sijms/go-ora/v2@v2.8.19/command.go:850 +0x12b5
github.com/sijms/go-ora/v2.(*defaultStmt)._fetch(0xc004ecd040, 0xc00048df00)
        /home/builder/go/pkg/mod/github.com/sijms/go-ora/v2@v2.8.19/command.go:667 +0x13b
github.com/sijms/go-ora/v2.(*defaultStmt).fetch(0xc004ecd040, 0xd33f20?)
        /home/builder/go/pkg/mod/github.com/sijms/go-ora/v2@v2.8.19/command.go:620 +0x55
github.com/sijms/go-ora/v2.(*DataSet).Next(0xc00048df00, {0xc0012656c0, 0x1a, 0x48e25d?})
        /home/builder/go/pkg/mod/github.com/sijms/go-ora/v2@v2.8.19/data_set.go:326 +0x1cd
database/sql.(*Rows).nextLocked(0xc0014ecfc0)
```

**Comment by rembosk8** [comment]
infinity value?
