### ISSUE TITLE
panic: runtime error: slice bounds out of range [-68:]

### ISSUE THREAD

**Issue by priyesh-mishra** [sijms/go-ora#624]
Even after upgrading to latest version 2.8.22 , i am encountering this error randomly .

`panic: runtime error: slice bounds out of range [-68:]

goroutine 17062169 [running]:
github.com/sijms/go-ora/v2/network.(*Session).GetInt64(0xc0001fcc40?, 0x1?, 0xfe?, 0xeb?)
	/root/go/pkg/mod/github.com/sijms/go-ora/v2@v2.8.22/network/session.go:1610 +0x192
github.com/sijms/go-ora/v2/network.(*Session).GetInt(...)
	/root/go/pkg/mod/github.com/sijms/go-ora/v2@v2.8.22/network/session.go:1626
github.com/sijms/go-ora/v2.(*defaultStmt).read(0xc0125c5680, 0xc001fc0a98)
	/root/go/pkg/mod/github.com/sijms/go-ora/v2@v2.8.22/command.go:931 +0x12e7
github.com/sijms/go-ora/v2.(*Stmt)._exec(0xc0125c5680, {0xc001fb4800, 0x17, 0xc000131360?})
	/root/go/pkg/mod/github.com/sijms/go-ora/v2@v2.8.22/command.go:1776 +0xaa8
github.com/sijms/go-ora/v2.(*Stmt).ExecContext(0xc0125c5680, {0xc6c7e8, 0xc0000400b8}, {0xc001fb4800, 0x17, 0x17})
	/root/go/pkg/mod/github.com/sijms/go-ora/v2@v2.8.22/command.go:1276 +0x1fc
github.com/sijms/go-ora/v2.(*Connection).ExecContext(0xc001fc1348?, {0xc6c7e8, 0xc0000400b8}, {0xb875fc?, 0x741c00?}, {0xc001fb4800, 0x17, 0x17})
	/root/go/pkg/mod/github.com/sijms/go-ora/v2@v2.8.22/connection.go:1112 +0x86
database/sql.ctxDriverExec({0xc6c7e8?, 0xc0000400b8?}, {0x7fbcb85a1068?, 0xc0001ec000?}, {0x0?, 0x0?}, {0xb875fc?, 0xb5ebfc?}, {0xc001fb4800, 0x17, ...})
	/usr/lib/golang/src/database/sql/ctxutil.go:31 +0xe5
database/sql.(*DB).execDC.func2()
	/usr/lib/golang/src/database/sql/sql.go:1679 +0x175
database/sql.withLock({0xc691a0, 0xc0001de090}, 0xc001fc1270)
	/usr/lib/golang/src/database/sql/sql.go:3439 +0x8c
database/sql.(*DB).execDC(0x0?, {0xc6c7e8, 0xc0000400b8}, 0xc0001de090, 0x18?, {0xb875fc, 0x1fc}, {0xc001fc1908, 0x17, 0x17})
	/usr/lib/golang/src/database/sql/sql.go:1674 +0x266
database/sql.(*Tx).ExecContext(0xc011d10300, {0xc6c7e8, 0xc0000400b8}, {0xb875fc, 0x1fc}, {0xc001fc1908, 0x17, 0x17})
	/usr/lib/golang/src/database/sql/sql.go:2491 +0xb7
database/sql.(*Tx).Exec(...)
	/usr/lib/golang/src/database/sql/sql.go:2500
main.insertAdpStagingData(0xc0000f0000?, {0xc01b7ea000?, 0x2b25?, 0x39?}, {0xc031339dc5, 0xc})
	/build/db.go:96 +0xf34
main.saveDataToDB({0x27?, 0xc001fc1cf0?}, 0xc00017eb00, {0xc031339dc5, 0xc}, {0xc01b7ea000, 0x2b25, 0x2c00}, {0xc00e816000, 0x2323, ...})
	/build/adp_core.go:40 +0x38c
main.getAndSaveRegionData({0xc6c7b0, 0xc000128200}, 0xc00017eb00, {0x39a, {0xc031339dc5, 0xc}, {0xc1cd84cc626bc95a, 0x326c7a3e5091, 0x1c81d00}, {0x0, ...}, ...})
	/build/app.go:323 +0x46c
main.concurrentGetAndSaveRegionData.func1({0x39a, {0xc031339dc5, 0xc}, {0xc1cd84cc626bc95a, 0x326c7a3e5091, 0x1c81d00}, {0x0, 0x0, 0x0}, {0x0, ...}, ...})
	/build/app.go:255 +0x225
created by main.concurrentGetAndSaveRegionData
	/build/app.go:244 +0x93`

**Comment by sijms** [comment]
would you please send me the query that produce this error
the error occur at the following line
```golang
if session.TTCVersion >= 7 && stmt.stmtType == DML && stmt.arrayBindCount > 0 {
	length, err := session.GetInt(4, true, true)
	if err != nil {
		return err
	}
	// for (int index = 0; index < length3; ++index)
	//	rowsAffectedByArrayBind[index] = this.m_marshallingEngine.UnmarshalSB8();
	for i := 0; i < length; i++ {
		_, err = session.GetInt(8, true, true)
		if err != nil {
			return err
		}
	}
}
```

**Comment by WolfEYc** [comment]
bump+1 I get this error as well
